name: Linters and Test

on:
  pull_request:
    branches:
      - develop
    types: [opened, edited, reopened, synchronize]
jobs:
  install-node-modules:
    name: Install Node Modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          cache: npm
      - name: Install packages
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_SECRET }}
      - name: Execute lint JS
        run: npm run lint
      - name: Execute lint CSS
        run: npm run lint:style
